{"name": "Проверка ошибки при попытке обновления данных неавторизованного пользователя", "status": "passed", "description": "Тест проверяет, что неавторизованный пользователь не может обновить данные и получает ошибку", "start": 1717347262992, "stop": 1717347263572, "uuid": "2da5e44e-ebed-4c1e-89a7-cba3fc8e5c60", "historyId": "db21696b705cc63a90f708d9817a8377", "testCaseId": "db21696b705cc63a90f708d9817a8377", "fullName": "tests.test_change_user_data.TestChangeUserData#test_user_cant_update_info_without_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_user_data"}, {"name": "subSuite", "value": "TestChangeUserData"}, {"name": "host", "value": "DESKTOP-212965U"}, {"name": "thread", "value": "10096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_user_data"}]}